In [1]:
import torch

In [3]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x.numel()

10

In [6]:
x.shape

torch.Size([10])

In [8]:
X = x.reshape(5,2)
X

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [9]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
torch.randn(3,4)

tensor([[-0.8677, -1.0507, -0.7400,  0.5692],
        [ 0.4141,  0.7752,  0.3298, -0.3996],
        [ 1.7857, -1.0600,  0.0463,  0.4585]])

In [12]:
torch.tensor([[2,3,2]])

tensor([[2, 3, 2]])

In [13]:
torch.tensor([[3,4,5],[3,3,4]])

tensor([[3, 4, 5],
        [3, 3, 4]])

In [14]:
torch.tensor([3,34,4])

tensor([ 3, 34,  4])

In [15]:
A = torch.arange(20).reshape(4,5)

In [16]:
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [17]:
A[0]

tensor([0, 1, 2, 3, 4])

In [18]:
A[-1]

tensor([15, 16, 17, 18, 19])

In [19]:
A[0:4]

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [20]:
A[0:3]

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [23]:
A[1:2, 1:2] = 99

In [24]:
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5, 99,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [26]:
torch.exp(A)

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02,        inf, 1.0966e+03, 2.9810e+03, 8.1031e+03],
        [2.2026e+04, 5.9874e+04, 1.6275e+05, 4.4241e+05, 1.2026e+06],
        [3.2690e+06, 8.8861e+06, 2.4155e+07, 6.5660e+07, 1.7848e+08]])

In [27]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)

In [29]:
Y = torch.tensor([[2,1,4,3], [1,2,3,4], [4, 3, 2, 1]])

In [30]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [32]:
torch.cat((X,Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [33]:
X > 5

tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])

In [34]:
torch.sum(X)

tensor(66.)

In [40]:
a = torch.arange(3).reshape((3,1))
a

tensor([[0],
        [1],
        [2]])

In [39]:
b = torch.arange(2).reshape((1,2))
b

tensor([[0, 1]])

In [41]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [44]:
before = id(Y)
before

1628845840480

In [45]:
Y = Y + X

In [46]:
id(Y)

1629695363488

In [48]:
Z = torch.zeros_like(Y)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
print("id(Z): ", id(Z))

id(Z):  1628845840240


In [50]:
Z[:] = X + Y
print("id Z ", id(Z))

id Z  1628845840240


In [51]:
Z = Z.numpy()
Z


array([[ 2.,  3.,  8.,  9.],
       [ 9., 12., 15., 18.],
       [20., 21., 22., 23.]], dtype=float32)

In [53]:
ZZ = torch.arange(5)

In [54]:
ZZ

tensor([0, 1, 2, 3, 4])

In [55]:
ZZnumpy = ZZ.numpy()
ZZnumpy

array([0, 1, 2, 3, 4], dtype=int64)

In [56]:
ZZbacktotorch = torch.from_numpy(ZZnumpy)

In [57]:
ZZbacktotorch

tensor([0, 1, 2, 3, 4])