In [6]:
import torch
x = torch.arange(4.0)

In [7]:
x

tensor([0., 1., 2., 3.])

In [8]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # The gradient is None by default

In [9]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [10]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [11]:
x.grad == 4 * x

tensor([True, True, True, True])

In [12]:
x.grad.zero_()
y= x * x
u = y.detach()
z = u * x

In [13]:
z.sum().backward()
x.grad == u

tensor([True, True, True, True])