In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(nn.LazyLinear(8),
                    nn.ReLU(),
                    nn.LazyLinear(1))

X = torch.rand(size=(2,4))
net(X).shape

C:\Users\david\miniconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

In [3]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.2194,  0.2415, -0.3293,  0.0343, -0.0347, -0.2623,  0.3030,  0.2897]])),
             ('bias', tensor([-0.1041]))])

In [4]:
type(net[2].bias), net[2].bias.data


(torch.nn.parameter.Parameter, tensor([-0.1041]))

In [5]:
net[2].bias

Parameter containing:
tensor([-0.1041], requires_grad=True)

In [6]:
net[2].bias.data

tensor([-0.1041])

In [8]:
net[2].weight.grad